import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Header: NextPage = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="p-1 border-b-2 border-black">
        <div className="flex justify-between text-xl">
          <h1 className="">Tech Blog</h1>
          <div>🔍</div>
          <div>三</div>
        </div>
      </header>
    </div>
  );
};

export default Header;
