import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Link from "next/link";
import { client } from "../libs/client";

type BlogItemList = {
  body: string;
  category: [];
  createdAt: string;
  id: string;
  image: {};
  publishedAt: string;
  revisedAt: string;
  title: string;
  updatedAt: string;
};

const Home: NextPage<BlogItemList> = ({ blog }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="m-2 p-5">
        <article>
          <div>
            <ul>
              {blog.map((blog) => (
                <li key={blog.id} className="mt-2 mb-6">
                  <Link href={`/blog/${blog.id}`}>
                    <a>
                      <div className="border-1 rounded-xl shadow-lg">
                        <img src={blog.image.url} alt="" />
                      </div>
                      <h1 className="m-2 text-sm">{blog.title}</h1>
                      <div className="flex">
                        {blog.category.map((tag: string) => (
                          <div key={tag}>
                            <p className="p-1 border-2 border-red-300 rounded-lg m-1 text-xs">
                              {tag}
                            </p>
                          </div>
                        ))}
                      </div>
                      <p className="m-1 text-xs">{blog.publishedAt}</p>
                    </a>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </article>
      </main>
    </div>
  );
};
export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "blog" });

  return {
    props: {
      blog: data.contents,
    },
  };
};
export default Home;
